Outlook set signature using event-based activation
OfficeDev/PnP-OfficeAddins pull request #126
Opened 2021-04-02 17:28 UTC by davidchesnut

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | yes                              |
| New sample?     | yes                               |
| Related issues? | no |

## What's in this Pull Request?

New sample to show how to use event-based activation in Outlook. Scenario shows how add-in can prompt user even when task pane is not showing. And lets user enter and save a signature that gets applied to messages and appointments.

2021-04-02 18:07 UTC, lindalu-MSFT requested changes
In a few code blocks, you're missing the closing ``` which extends the code formatting to non-code text. I also moved the **Applies to:** section to the top, and added NOTE format.

2021-04-02 18:07 UTC, lindalu-MSFT commented on Samples/outlook-set-signature/README.md
> +The `autorunweb.js` file contains a version of the `insert_auto_signature` function used specifically when running on Outlook on the web. The [setSignatureAsync() API cannot be used in Outlook on the
```suggestion
The `autorunweb.js` file contains a version of the `insert_auto_signature` function used specifically when running on Outlook on the web. The [setSignatureAsync() API cannot be used in Outlook on the web for appointments](https://docs.microsoft.com/javascript/api/outlook/office.body?view=outlook-js-preview#setSignatureAsync_data__options__callback_). Therefore, `insert_auto_signature` inserts the signature into a new appointment by directly writing to the body text of the appointment.
```

2021-04-02 18:07 UTC, lindalu-MSFT commented on Samples/outlook-set-signature/README.md
> +Note that you can use a similar pattern when handling events. If you need code that only applies to Outlook on the web, you can load it in a separate file like `autorunweb.js`. And for code that appl
```suggestion
> [!NOTE]
> You can use a similar pattern when handling events. If you need code that only applies to Outlook on the web, you can load it in a separate file like `autorunweb.js`. And for code that applies to both Outlook on the web and Outlook on Windows, you can load it in a shared file like `autorunshared.js`.
```

2021-04-02 18:07 UTC, lindalu-MSFT commented on Samples/outlook-set-signature/README.md
> +You can install or uninstall the certificates by running the following commands in the project folder.
```suggestion
Install or uninstall the certificates by running the following commands in the project folder.
```

2021-04-02 23:50 UTC, davidchesnut commented on Samples/outlook-set-signature/README.md
> +- office-365
yep, thanks!

2021-04-02 23:54 UTC, davidchesnut commented on Samples/outlook-set-signature/README.md
> +----------
It's an old format from legal guidelines that I'm looking into to see if we can change soon.

2021-04-02 23:57 UTC, davidchesnut commented on Samples/outlook-set-signature/README.md
> +## Applies to
fixed

2021-04-02 23:58 UTC, davidchesnut commented on Samples/outlook-set-signature/README.md
> +> **Note:** The features used in this sample are currently in preview and subject to change. They are not currently supported for use in production environments. To try the preview features, you'll n
not in docs.

2021-04-05 15:52 UTC, lindalu-MSFT approved these changes

2021-04-06 00:25 UTC, merged