[Outlook](SSO) Move and update Outlook SSO sample to this repo
OfficeDev/PnP-OfficeAddins pull request #135
Opened 2021-05-06 17:02 UTC by davidchesnut

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                              |
| New sample?     | no                                |
| Related issues? | none |

## What's in this Pull Request?

This PR moves the Outlook SSO sample into this PnP repo (from: https://github.com/OfficeDev/Outlook-Add-in-SSO)

It also updates the Outlook SSO sample to use latest MSAL and also just has general code cleanup work.

2021-05-06 17:03 UTC, davidchesnut commented
Would be great to have folks follow the readme and ensure this sample is working as expected! Thanks!

2021-05-06 19:18 UTC, Rick-Kirkham requested changes
Biggest issue is that there's no proper error handling for the call of getAccessToken and no branching to the fallback method. 
Also, the files don't save. 
See my specific comments.

2021-05-06 19:18 UTC, Rick-Kirkham commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +Press **F5** to build and debug the project. You should be prompted for a user account and password. Be sure to use a user in your Office 365 tenant, or an Outlook.com account. The add-in will be ins
```suggestion
Press **F5** to build and debug the project. You should be prompted for a user account and password. Be sure to use a user in your Office 365 tenant, or an Outlook.com account. The add-in will be installed for that user, and either Outlook on the web or Outlook will open. Select any message **that has one or more attachments**, and you should see the add-in buttons on the Outlook ribbon.
```

2021-05-06 19:18 UTC, Rick-Kirkham commented on Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Functions/FunctionFile.js
> +    let accessToken = await OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true, allowConsentPrompt: true, forMSGraphAccess: true });
There's no error handling for the call to getAccessToken and no branching to the fallback method when the call fails.

2021-05-21 21:49 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +    - `d3590ed6-52b3-4102-aeff-aad2292ab01c` (Microsoft Office)
added.

2021-05-22 19:39 UTC, Rick-Kirkham commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +        > [!NOTE]
Still needs to be fixed.

2021-05-22 20:57 UTC, Rick-Kirkham commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +Edit [Web.config](AttachmentDemoWeb/Web.config) and replace the `[Enter the Client Id (Application ID obtained from the Azure portal)]` value in with the application ID and `[Copy the client secret a
Still needs to be fixed.

2021-05-23 01:02 UTC, Rick-Kirkham requested changes

2021-05-26 17:12 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +
I added this info to the readme.

2021-05-26 17:12 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +
Ok, added steps and screen shots.

2021-05-26 17:12 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +1. In the **Solution Explorer** open **AttachmentDemoWeb > Web.config** and replace the `[Enter the Client Id (Application ID obtained from the Azure portal)]` value with the application ID and `[Cop
fixed

2021-05-26 17:12 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +        **Note:** The port number in the redirect URI (`44355`) may be different on your development machine. You can find the correct port number for your machine by selecting the **AttachmentDemoWe
fixed.

2021-05-26 17:12 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Controllers/AzureADAuthController.cs
> +			string[] graphScopes = { "https://graph.microsoft.com/Files.Read.All", "https://graph.microsoft.com/User.Read" };
fixed to use the correct scopes

2021-05-26 17:13 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Functions/FunctionFile.js
> +    let accessToken = await OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true, allowConsentPrompt: true, forMSGraphAccess: true });
removed this from the sample.

2021-05-26 17:13 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Controllers/SaveAttachmentsController.cs
> +            string[] graphScopes = { "https://graph.microsoft.com/Files.Read.All" };
fixed to request correct scopes

2021-05-26 17:13 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Scripts/MessageRead.js
> +            saveAttachmentsWithSSO("/api/saveAttachmentsFallback", message.accessToken, attachmentIds);
did some refactoring to make this all clearer.

2021-05-26 17:13 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Scripts/MessageRead.js
> +    function saveAttachmentsWithSSO(relativeURL, accessToken, attachmentIds) {
fixed.

2021-05-26 17:13 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/AttachmentDemoWeb/Scripts/MessageRead.js
> +            // The /api/saveAttachmentsToOneDrive controller will make the token exchange and use the
fixed.

2021-05-26 17:13 UTC, davidchesnut commented on Samples/auth/Outlook-Add-in-SSO/README.md
> +        > [!NOTE]
fixed.

2021-05-26 19:46 UTC, Rick-Kirkham approved these changes

2021-05-28 23:50 UTC, merged